
server :
  port : 9000

eureka :
  client :
    serviceUrl :
      defaultZone : http://localhost:9083/eureka

spring :
  application :
    name : gateway-service
  cloud :
    gateway :
      routes : 
        - id : employeeModule
          uri : lb://FIRST-SERVICE
          predicates : 
            - Path=/employee/**

        - id : consumerModule
          uri : lb://SECOND-SERVICE
          predicates : 
            - Path=/consumer/**